version: '3.8'

volumes:
  postgres-data:

networks:
  api:
  database:

services:
  db:
    container_name: postgres-sandbox
    restart: always
    build:
      context: ./northwind_psql_sql_example
      target: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/bitnami/postgresql/data
    networks:
      - database
        
  graphql-server:
    container_name: graphql-sandbox
    depends_on:
      - db
    build:
      context: ./microservice-graphql-example
      target: graphql-server
    ports:
    -  "4000:4000"
    networks:
      - database
      - api