version: '3.8'

volumes:
  postgres-db:

services:
  db:
    container_name: postgres-sandbox
    build:
      context: .
      target: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /test-volume
  graphql-server:
    container_name: graphql-sandbox
    depends_on:
      - db
    build:
      context: .
      target: graphql-server
    ports:
    -  "4000:4000"